### ISSUE TITLE
Support for Streams

### ISSUE THREAD

**Issue by dmarjenburgh** [ptaoussanis/faraday#107]
I would like to request support for DynamoDB Streams, I'm currently missing it in faraday.

I have already implemented the streams api functions here:
https://github.com/ptaoussanis/faraday/compare/master...dmarjenburgh:support-for-dynamodbstreams?expand=0#diff-661b1918412a069505ca2755d39c63e4

This is basically a wrapper around the low-level Java api. I think it's good to expose these and then maybe build a higher level api on top later.
Not too sure about the namings or Java Object<->Clojure map conversions. I decided to keep close to the original API (For example, sequence-range is a map with :sequence-start-number and :sequence-end-number, whose values are strings).

Shall I open a pull-request for this?

**Comment by ricardojmendez** [comment]
Hi!

Thanks for writing. I haven't used the streams myself, so I'm not that familiar with them. Is this something you can add tests for using the local DynamoDB, or do they only work on full version?

**Comment by dmarjenburgh** [comment]
They work for the local version as well (small differences at the bottom of [Usage Notes](http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBLocal.UsageNotes.html).

I'm not familiar with the test namespaces in farady, so I'm not sure how easy it is to write tests for this, but I can have a look

**Comment by ricardojmendez** [comment]
Thanks! Alternatively, as discussed on #101 we might just move away from `expectations`, so I expect it'd be fine just having a namespace for these tests based on `clojure.test`.  I'll let @ptaoussanis chime in, though.

**Comment by dmarjenburgh** [comment]
Ok, I created some tests at the end of main.clj.
Let me know if and how it needs to be improved.

**Comment by ptaoussanis** [comment]
Thanks Daniel, Ricardo!

> so I expect it'd be fine just having a namespace for these tests based on clojure.test

My 2c: might suggest that we continue just using Expectations for everything for the moment, until everything gets migrated in one go. [Indeed, may never even happen since it's not urgent or particularly valuable].

Migrating between Expectations and clojure.test should be straight-forward if/when we choose to do it; probably even something we can do programatically.

Splitting tests between two tools (even temporarily) might cause more hassle than it's worth?

Thanks for checking about this though, was a totally reasonable suggestion after our recent chat about the test situation.

----

Re: the PR in general-

Only had an opportunity to skim, but looks good to me in principle. @ricardojmendez How about you let me know when you're satisfied with the PR, and I'll give it one last look-over before we merge?

Really appreciate both your efforts, this looks like it'll be a valuable addition.

Cheers! :-)

**Comment by ricardojmendez** [comment]
> Migrating between Expectations and clojure.test should be straight-forward if/when we choose to do it; probably even something we can do programatically.
>
> Splitting tests between two tools (even temporarily) might cause more hassle than it's worth?

Playing devil's advocate, since I'm ambivalent myself about the idea of keeping two frameworks while transitioning:

- Splitting tests has a small, one-time cost: making sure both are run on the test script,
- Allowing people to contribute self-contained tests via  `clojure.test` lowers the barrier of entry for contributors who might not be familiar with expectations, or who potentially don't want to wade through our current test monolith,
- Contributors are more likely to be aware of the intention of their change than us, so it makes sense to minimize the odds of running into an issue when eventually migrating their tests.

Let me go over the PR later today.

**Comment by ptaoussanis** [comment]
> Playing devil's advocate, [...]

Appreciate that, thanks. Will just note that migrating away from Expectations is low enough a priority that there's a significant chance it may never happen. Meaning that we may need to be okay with potentially being stuck with two test suites + tools moving forward.

Don't have a strong preference on this, happy for you to make the call.

**Comment by ptaoussanis** [comment]
Closing to focus on #108
